//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBSACHEntities : DbContext
    {
        public QLBSACHEntities()
            : base("name=QLBSACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHDS> ChiTietHDS { get; set; }
        public virtual DbSet<ChiTietPNS> ChiTietPNS { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBan { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhap { get; set; }
        public virtual DbSet<Sach> Sach { get; set; }
        public virtual DbSet<TacGia> TacGia { get; set; }
        public virtual DbSet<TheLoai> TheLoai { get; set; }
    
        public virtual ObjectResult<string> pr_TIM_KIEM(string tenTL)
        {
            var tenTLParameter = tenTL != null ?
                new ObjectParameter("TenTL", tenTL) :
                new ObjectParameter("TenTL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_TIM_KIEM", tenTLParameter);
        }
    
        public virtual int pr_THEM_SACH(string maSach, string tenSach, string tenTG, Nullable<System.DateTime> ngayXB, string maTL)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var tenTGParameter = tenTG != null ?
                new ObjectParameter("TenTG", tenTG) :
                new ObjectParameter("TenTG", typeof(string));
    
            var ngayXBParameter = ngayXB.HasValue ?
                new ObjectParameter("NgayXB", ngayXB) :
                new ObjectParameter("NgayXB", typeof(System.DateTime));
    
            var maTLParameter = maTL != null ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_THEM_SACH", maSachParameter, tenSachParameter, tenTGParameter, ngayXBParameter, maTLParameter);
        }
    
        public virtual int pr_XOA_SACH(string maSach)
        {
            var maSachParameter = maSach != null ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_XOA_SACH", maSachParameter);
        }
    }
}
