//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string SoHD { get; set; }
        public string MaHDS { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string MaKH { get; set; }
    
        public virtual ChiTietHDS ChiTietHDS { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
