//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string SoPN { get; set; }
        public string SoCTPNS { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string MaNCC { get; set; }
    
        public virtual ChiTietPNS ChiTietPNS { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
